namespace f3dzex2.displaylist {
  /**
   * https://hack64.net/wiki/doku.php?id=super_mario_64:fast3d_display_list_commands
   */
  public enum F3dOpcode : byte {
    G_SPNOOP = 0x00,
    G_MTX = 0x01,
    G_MOVEMEM = 0x03,
    G_VTX = 0x04,
    G_DL = 0x06,
    G_RDPHALF_CONT = 0xB2,
    G_RDPHALF_2 = 0xB3,
    G_RDPHALF_1 = 0xB4,
    G_CLEARGEOMETRYMODE = 0xB6,
    G_SETGEOMETRYMODE = 0xB7,
    G_ENDDL = 0xB8,
    G_SETOTHERMODE_L = 0xB9,
    G_SETOTHERMODE_H = 0xBA,
    G_TEXTURE = 0xBB,
    G_MOVEWORD = 0xBC,
    G_POPMTX = 0xBD,
    G_CULLDL = 0xBE,
    G_TRI1 = 0xBF,
    G_NOOP = 0xC0,
    G_TEXRECT = 0xE4,
    G_TEXRECTFLIP = 0xE5,
    G_RDPLOADSYNC = 0xE6,
    G_RDPPIPESYNC = 0xE7,
    G_RDPTILESYNC = 0xE8,
    G_RDPFULLSYNC = 0xE9,
    G_SETKEYGB = 0xEA,
    G_SETKEYR = 0xEB,
    G_SETCONVERT = 0xEC,
    G_SETSCISSOR = 0xED,
    G_SETPRIMDEPTH = 0xEE,
    G_RDPSETOTHERMODE = 0xEF,
    G_LOADTLUT = 0xF0,
    G_SETTILESIZE = 0xF2,
    G_LOADBLOCK = 0xF3,
    G_LOADTILE = 0xF4,
    G_SETTILE = 0xF5,
    G_FILLRECT = 0xF6,
    G_SETFILLCOLOR = 0xF7,
    G_SETFOGCOLOR = 0xF8,
    G_SETBLENDCOLOR = 0xF9,
    G_SETPRIMCOLOR = 0xFA,
    G_SETENVCOLOR = 0xFB,
    G_SETCOMBINE = 0xFC,
    G_SETTIMG = 0xFD,
    G_SETZIMG = 0xFE,
    G_SETCIMG = 0xFF,
  }
}
